# Generated by Django 5.1.5 on 2026-08-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_email_lower_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified_at",
            field=models.DateTimeField(
                blank=True,
                db_comment="인증 메일 링크를 확인한 시각. NULL 이면 미인증 (로그인 불가)",
                null=True,
                verbose_name="이메일 인증 시각",
            ),
        ),
    ]
