# Generated by Django 5.1.5 on 2026-08-26 08:25

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_grandfather_email_verified"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("nickname"),
                name="accounts_user_nickname_lower_uniq",
            ),
        ),
    ]
