# Generated by Django 5.1.5 on 2026-08-27 08:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_user_nickname_lower_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("kakao", "카카오")],
                        db_comment="소셜 제공자 (kakao)",
                        max_length=20,
                    ),
                ),
                (
                    "provider_uid",
                    models.CharField(
                        db_comment="제공자 쪽 사용자 ID (카카오 회원번호)",
                        max_length=64,
                    ),
                ),
                (
                    "email_at_provider",
                    models.EmailField(
                        blank=True,
                        db_comment="연결 당시 제공자에 등록된 이메일 (참고용)",
                        max_length=254,
                    ),
                ),
                (
                    "nickname_at_provider",
                    models.CharField(
                        blank=True,
                        db_comment="연결 당시 제공자 닉네임 (참고용)",
                        max_length=100,
                    ),
                ),
                (
                    "connected_at",
                    models.DateTimeField(
                        db_comment="연결(최초 로그인) 시각",
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="생성 시각", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_comment="마지막 수정 시각"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="soft delete 여부 (True면 삭제된 행)",
                        db_index=True,
                        default=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_comment="soft delete 시각", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_comment="회원 FK",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table_comment": "소셜 로그인 연결 — provider 토큰은 저장하지 않는다",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_deleted", False)),
                        fields=("provider", "provider_uid"),
                        name="accounts_socialaccount_provider_uid_uniq",
                    )
                ],
            },
        ),
    ]
