# Generated by Django 5.1.5 on 2026-08-27 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_social_account"),
        ("crews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="main_crew",
            field=models.ForeignKey(
                blank=True,
                db_comment="대표 크루 FK (활동 중인 크루 중 1개). 탈퇴·강퇴·크루 삭제 시 NULL",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="main_profiles",
                to="crews.crew",
            ),
        ),
    ]
