# Generated by Django 5.1.5 on 2026-08-27 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("like", "좋아요"),
                            ("comment", "댓글"),
                            ("reply", "답글"),
                            ("follow", "팔로우"),
                            ("recruitment_closed", "모집 마감"),
                            ("recruitment_approved", "모집 참여 승인"),
                            ("recruitment_rejected", "모집 참여 거절"),
                            ("crew_approved", "크루 가입 승인"),
                            ("crew_rejected", "크루 가입 거절"),
                            ("crew_joined", "크루 가입/신청 (운영진용)"),
                        ],
                        db_comment="알림 종류 (like/comment/…)",
                        max_length=30,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("climb_log", "등반 기록"),
                            ("post", "게시글"),
                            ("recruitment", "모집"),
                            ("crew", "크루"),
                            ("user", "회원"),
                        ],
                        db_comment="이동 대상 종류 (climb_log/post/recruitment/crew/user)",
                        max_length=20,
                    ),
                ),
                (
                    "target_id",
                    models.PositiveBigIntegerField(db_comment="이동 대상 id"),
                ),
                (
                    "message",
                    models.CharField(
                        db_comment="렌더링된 한국어 알림 문구 (최대 200자)",
                        max_length=200,
                    ),
                ),
                ("is_read", models.BooleanField(db_comment="읽음 여부", default=False)),
                (
                    "read_at",
                    models.DateTimeField(blank=True, db_comment="읽은 시각", null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="생성 시각", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_comment="마지막 수정 시각"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="soft delete 여부 (True면 삭제된 행)",
                        db_index=True,
                        default=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_comment="soft delete 시각", null=True
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        db_comment="행위자 FK (좋아요 누른 사람 등). 시스템 알림이면 NULL",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acted_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        db_comment="받는 회원 FK",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table_comment": "인앱 알림 — 받는 회원/행위자/종류/이동 대상/문구/읽음",
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read", "-created_at"],
                        name="notificatio_recipie_684eac_idx",
                    ),
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="notificatio_recipie_a972ce_idx",
                    ),
                ],
            },
        ),
    ]
