# Generated by Django 5.1.5 on 2026-08-28 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "push_enabled",
                    models.BooleanField(
                        db_comment="Web Push 팬아웃 허용 여부", default=True
                    ),
                ),
                (
                    "email_enabled",
                    models.BooleanField(
                        db_comment="이메일 팬아웃 허용 여부 (중요 알림만 발송)",
                        default=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="생성 시각", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_comment="마지막 수정 시각"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="soft delete 여부 (True면 삭제된 행)",
                        db_index=True,
                        default=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_comment="soft delete 시각", null=True
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        db_comment="회원 FK (1:1)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_setting",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table_comment": "회원별 알림 채널 설정 — 푸시/이메일 on·off",
            },
        ),
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "endpoint",
                    models.URLField(
                        db_comment="푸시 서비스 endpoint URL (브라우저별 고유)",
                        max_length=500,
                    ),
                ),
                (
                    "p256dh",
                    models.CharField(
                        db_comment="클라이언트 공개키 (keys.p256dh, base64url)",
                        max_length=255,
                    ),
                ),
                (
                    "auth",
                    models.CharField(
                        db_comment="인증 비밀 (keys.auth, base64url)", max_length=255
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        db_comment="구독 당시 User-Agent (기기 식별용)",
                        max_length=255,
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="마지막으로 푸시 발송에 성공한 시각",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="생성 시각", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_comment="마지막 수정 시각"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="soft delete 여부 (True면 삭제된 행)",
                        db_index=True,
                        default=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_comment="soft delete 시각", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_comment="구독한 회원 FK",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table_comment": "Web Push 구독 — 회원/endpoint/키/UA/마지막 사용",
                "indexes": [
                    models.Index(fields=["user"], name="notificatio_user_id_d7f78b_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_deleted", False)),
                        fields=("endpoint",),
                        name="uniq_push_subscription_endpoint",
                    )
                ],
            },
        ),
    ]
