# Generated by Django 5.1.5 on 2026-08-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notificationsetting_pushsubscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("like", "좋아요"),
                    ("comment", "댓글"),
                    ("reply", "답글"),
                    ("follow", "팔로우"),
                    ("recruitment_closed", "모집 마감"),
                    ("recruitment_approved", "모집 참여 승인"),
                    ("recruitment_rejected", "모집 참여 거절"),
                    ("crew_approved", "크루 가입 승인"),
                    ("crew_rejected", "크루 가입 거절"),
                    ("crew_joined", "크루 가입/신청 (운영진용)"),
                    ("crew_owner", "크루장 위임"),
                    ("analysis_done", "자세 분석 완료"),
                    ("analysis_failed", "자세 분석 실패"),
                    ("report_done", "코칭 리포트 완료"),
                    ("report_failed", "코칭 리포트 실패"),
                ],
                db_comment="알림 종류 (like/comment/…)",
                max_length=30,
            ),
        ),
    ]
