# Generated by Django 5.1.5 on 2026-08-27 08:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_group",
                    models.BooleanField(
                        db_comment="그룹 채팅 여부 (False 면 1:1 DM)", default=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        db_comment="방 이름 (1:1 은 빈 문자열)",
                        max_length=100,
                    ),
                ),
                (
                    "direct_key",
                    models.CharField(
                        blank=True,
                        db_comment="1:1 방 중복 방지 키 '{min_user_id}:{max_user_id}'. 그룹 방은 NULL",
                        max_length=41,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="생성 시각", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_comment="마지막 수정 시각"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="soft delete 여부 (True면 삭제된 행)",
                        db_index=True,
                        default=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_comment="soft delete 시각", null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="방을 만든 회원 FK (탈퇴 시 NULL)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_chat_rooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table_comment": "채팅방 — 1:1 은 direct_key 로 유일, 그룹은 이름 보유",
            },
        ),
        migrations.CreateModel(
            name="ChatRoomMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_read_message_id",
                    models.PositiveBigIntegerField(
                        blank=True,
                        db_comment="마지막으로 읽은 메시지 id (NULL 이면 하나도 안 읽음)",
                        null=True,
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        db_comment="입장 시각 (재입장 시 갱신)",
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="생성 시각", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_comment="마지막 수정 시각"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="soft delete 여부 (True면 삭제된 행)",
                        db_index=True,
                        default=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_comment="soft delete 시각", null=True
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        db_comment="방 FK",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="chat.chatroom",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_comment="참여 회원 FK",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table_comment": "채팅방 참여자 — (방, 회원) 유일, 읽음 위치 보관",
                "indexes": [
                    models.Index(
                        fields=["user", "room"], name="chat_chatro_user_id_8f00f2_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_deleted", False)),
                        fields=("room", "user"),
                        name="uniq_chat_room_member",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("text", "일반"), ("system", "시스템")],
                        db_comment="text | system",
                        default="text",
                        max_length=10,
                    ),
                ),
                ("content", models.TextField(db_comment="본문 (최대 2000자)")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="생성 시각", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_comment="마지막 수정 시각"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="soft delete 여부 (True면 삭제된 행)",
                        db_index=True,
                        default=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_comment="soft delete 시각", null=True
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        db_comment="방 FK",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.chatroom",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        db_comment="보낸 회원 FK. NULL 이면 시스템 메시지",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table_comment": "채팅 메시지 — 방별 id 역순 조회",
                "indexes": [
                    models.Index(
                        fields=["room", "-id"], name="chat_messag_room_id_de6b4b_idx"
                    )
                ],
            },
        ),
    ]
