# Generated by Django 5.1.5 on 2026-08-27 06:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gyms", "0002_location_column_comment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClimbLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_success",
                    models.BooleanField(db_comment="완등 여부", default=False),
                ),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        db_comment="시도 횟수 (1 이상)",
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("memo", models.TextField(blank=True, db_comment="메모 (최대 1000자)")),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        db_comment="등반 영상 URL (S3, presigned URL 로 직접 업로드)",
                    ),
                ),
                (
                    "climbed_at",
                    models.DateField(
                        db_comment="등반한 날짜 (미래 불가)",
                        default=django.utils.timezone.localdate,
                    ),
                ),
                (
                    "is_shared",
                    models.BooleanField(
                        db_comment="피드 공개 여부. False 면 본인만 조회", default=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="생성 시각", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_comment="마지막 수정 시각"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="soft delete 여부 (True면 삭제된 행)",
                        db_index=True,
                        default=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_comment="soft delete 시각", null=True
                    ),
                ),
                (
                    "difficulty",
                    models.ForeignKey(
                        blank=True,
                        db_comment="난이도 FK (암장별 색 난이도). 암장이 난이도를 지우면 NULL",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="climb_logs",
                        to="gyms.gymdifficulty",
                    ),
                ),
                (
                    "gym",
                    models.ForeignKey(
                        db_comment="등반한 암장 FK",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="climb_logs",
                        to="gyms.gym",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_comment="작성자 FK",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="climb_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table_comment": "등반 기록 — 암장/난이도/성공 여부/메모/영상. 공개분은 피드에 노출",
            },
        ),
        migrations.CreateModel(
            name="ClimbLogComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(db_comment="댓글 본문 (최대 500자)")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="생성 시각", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_comment="마지막 수정 시각"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="soft delete 여부 (True면 삭제된 행)",
                        db_index=True,
                        default=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_comment="soft delete 시각", null=True
                    ),
                ),
                (
                    "climb_log",
                    models.ForeignKey(
                        db_comment="기록 FK",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="climbs.climblog",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_comment="부모 댓글 FK — 1단계 대댓글만 허용 (대댓글의 대댓글 불가)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="climbs.climblogcomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_comment="작성자 FK",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="climb_log_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table_comment": "등반 기록 댓글 — parent 로 1단계 대댓글",
            },
        ),
        migrations.CreateModel(
            name="ClimbLogLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="생성 시각", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_comment="마지막 수정 시각"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="soft delete 여부 (True면 삭제된 행)",
                        db_index=True,
                        default=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_comment="soft delete 시각", null=True
                    ),
                ),
                (
                    "climb_log",
                    models.ForeignKey(
                        db_comment="기록 FK",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="climbs.climblog",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_comment="좋아요 누른 회원 FK",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="climb_log_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table_comment": "등반 기록 좋아요 — (기록, 회원) 유일",
            },
        ),
        migrations.AddIndex(
            model_name="climblog",
            index=models.Index(
                fields=["user", "-created_at"], name="climbs_clim_user_id_86cc4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="climblog",
            index=models.Index(
                fields=["gym", "-created_at"], name="climbs_clim_gym_id_fe21ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="climblog",
            index=models.Index(
                fields=["is_shared", "-created_at"],
                name="climbs_clim_is_shar_e79b75_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="climblogcomment",
            index=models.Index(
                fields=["climb_log", "created_at"],
                name="climbs_clim_climb_l_0d2c8b_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="climbloglike",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("climb_log", "user"),
                name="uniq_climb_log_like",
            ),
        ),
    ]
