# Generated by Django 5.1.5 on 2026-08-28 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("climbs", "0001_initial"),
        ("gyms", "0002_location_column_comment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClimbBeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sector",
                    models.CharField(
                        blank=True,
                        db_comment="섹터/벽 이름 (예: A섹터, 슬랩 벽) — 자유 문자열, 세팅마다 바뀜",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(db_comment="베타 제목", max_length=100)),
                (
                    "description",
                    models.TextField(blank=True, db_comment="설명 (최대 1000자)"),
                ),
                (
                    "video_url",
                    models.URLField(
                        db_comment="베타 영상 URL (S3, presigned URL 로 직접 업로드). 생성 후 변경 불가"
                    ),
                ),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, db_comment="썸네일 이미지 URL (S3)"),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        db_comment="조회수 — 상세 조회 때마다 F() 로 원자적 증가",
                        default=0,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="생성 시각", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_comment="마지막 수정 시각"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="soft delete 여부 (True면 삭제된 행)",
                        db_index=True,
                        default=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_comment="soft delete 시각", null=True
                    ),
                ),
                (
                    "climb_log",
                    models.ForeignKey(
                        blank=True,
                        db_comment="연결된 본인 등반 기록 FK (선택, 같은 암장 기록만)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="betas",
                        to="climbs.climblog",
                    ),
                ),
                (
                    "difficulty",
                    models.ForeignKey(
                        blank=True,
                        db_comment="난이도 FK (암장별 색 난이도). 암장이 난이도를 지우면 NULL",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="betas",
                        to="gyms.gymdifficulty",
                    ),
                ),
                (
                    "gym",
                    models.ForeignKey(
                        db_comment="암장 FK",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="betas",
                        to="gyms.gym",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_comment="올린 회원 FK",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="climb_betas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table_comment": "암장 섹터별 베타 영상 — 섹터/난이도/제목/영상. 조회는 공개",
                "indexes": [
                    models.Index(
                        fields=["gym", "-created_at"],
                        name="climbs_clim_gym_id_fc41bc_idx",
                    ),
                    models.Index(
                        fields=["gym", "sector"], name="climbs_clim_gym_id_34a5a9_idx"
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="climbs_clim_user_id_30d3f4_idx",
                    ),
                ],
            },
        ),
    ]
