# Generated by Django 5.1.5 on 2026-08-27 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("climbs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("processing", "분석 중"),
                            ("done", "완료"),
                            ("failed", "실패"),
                        ],
                        db_comment="pending(대기) / processing(분석 중) / done(완료) / failed(실패)",
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        db_comment="실패 사유 (사용자에게 그대로 보여줄 수 있는 짧은 문장)",
                    ),
                ),
                (
                    "keypoints",
                    models.JSONField(
                        blank=True,
                        db_comment='샘플링 프레임별 MediaPipe Pose 33 랜드마크. {"fps": n, "frames": [{"t": 초, "lm": [[x, y, z, vis] × 33] | null}]}',
                        default=dict,
                    ),
                ),
                (
                    "metrics",
                    models.JSONField(
                        blank=True,
                        db_comment="지표 요약 — 무게중심 궤적/이동 거리/상승량, 관절 각도 통계, 무브 비율, 길이",
                        default=dict,
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, db_comment="분석 완료(done) 시각", null=True
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveSmallIntegerField(
                        db_comment="워커 재시도 횟수 (네트워크성 실패만 1회 재시도)",
                        default=0,
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True,
                        db_comment="마지막으로 큐에 넣은 Celery task id",
                        max_length=64,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="생성 시각", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_comment="마지막 수정 시각"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="soft delete 여부 (True면 삭제된 행)",
                        db_index=True,
                        default=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_comment="soft delete 시각", null=True
                    ),
                ),
                (
                    "climb_log",
                    models.OneToOneField(
                        db_comment="분석 대상 등반 기록 FK (기록당 1건)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="climbs.climblog",
                    ),
                ),
            ],
            options={
                "db_table_comment": "등반 영상 AI 자세 분석 — 기록당 1건, 상태/랜드마크/지표",
            },
        ),
    ]
