# Generated by Django 5.1.5 on 2026-08-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoanalysis",
            name="report",
            field=models.TextField(
                blank=True,
                db_comment="LLM 이 생성한 코칭 리포트 본문 (한국어 markdown)",
            ),
        ),
        migrations.AddField(
            model_name="videoanalysis",
            name="report_error",
            field=models.TextField(
                blank=True,
                db_comment="리포트 생성 실패 사유 (사용자에게 보여줄 수 있는 문장)",
            ),
        ),
        migrations.AddField(
            model_name="videoanalysis",
            name="report_generated_at",
            field=models.DateTimeField(
                blank=True, db_comment="리포트 생성 완료(done) 시각", null=True
            ),
        ),
        migrations.AddField(
            model_name="videoanalysis",
            name="report_input_tokens",
            field=models.PositiveIntegerField(
                db_comment="리포트 생성에 쓴 입력 토큰 수", default=0
            ),
        ),
        migrations.AddField(
            model_name="videoanalysis",
            name="report_model",
            field=models.CharField(
                blank=True,
                db_comment="리포트를 생성한 LLM 모델 id (응답 기준)",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="videoanalysis",
            name="report_output_tokens",
            field=models.PositiveIntegerField(
                db_comment="리포트 생성에 쓴 출력 토큰 수", default=0
            ),
        ),
        migrations.AddField(
            model_name="videoanalysis",
            name="report_status",
            field=models.CharField(
                choices=[
                    ("none", "미생성"),
                    ("pending", "대기"),
                    ("processing", "생성 중"),
                    ("done", "완료"),
                    ("failed", "실패"),
                ],
                db_comment="코칭 리포트 상태 — none(미생성)/pending/processing/done/failed",
                db_index=True,
                default="none",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="videoanalysis",
            name="report_task_id",
            field=models.CharField(
                blank=True,
                db_comment="마지막으로 큐에 넣은 리포트 생성 Celery task id",
                max_length=64,
            ),
        ),
    ]
