# Generated by Django 5.1.5 on 2026-08-27 08:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0001_initial"),
        ("gyms", "0002_location_column_comment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Crew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="크루 이름 (중복 불가, 최대 30자)",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True, db_comment="크루 소개")),
                (
                    "image",
                    models.URLField(blank=True, db_comment="대표 이미지 URL (S3)"),
                ),
                (
                    "join_type",
                    models.CharField(
                        choices=[("instant", "즉시 가입"), ("approval", "승인제")],
                        db_comment="가입 방식 (instant 즉시 가입 / approval 운영진 승인제)",
                        default="instant",
                        max_length=10,
                    ),
                ),
                (
                    "max_members",
                    models.PositiveSmallIntegerField(
                        db_comment="최대 인원 (크루장 포함, 2~200명)",
                        default=30,
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            django.core.validators.MaxValueValidator(200),
                        ],
                    ),
                ),
                (
                    "is_feed_public",
                    models.BooleanField(
                        db_comment="크루 피드 공개 여부 (False 면 활동 중인 크루원만 조회)",
                        default=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="생성 시각", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_comment="마지막 수정 시각"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="soft delete 여부 (True면 삭제된 행)",
                        db_index=True,
                        default=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_comment="soft delete 시각", null=True
                    ),
                ),
                (
                    "chat_room",
                    models.OneToOneField(
                        db_comment="크루 단톡방 FK — 크루 생성 시 자동 생성",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="crew",
                        to="chat.chatroom",
                    ),
                ),
                (
                    "home_gym",
                    models.ForeignKey(
                        blank=True,
                        db_comment="주 활동 암장 FK (선택). 암장이 지워지면 NULL",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crews",
                        to="gyms.gym",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        db_comment="크루장 FK",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_crews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table_comment": "클라이밍 크루 — 이름 유일, 단톡방 1:1, 가입 방식/정원",
            },
        ),
        migrations.CreateModel(
            name="CrewMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "크루장"),
                            ("staff", "운영진"),
                            ("member", "크루원"),
                        ],
                        db_comment="역할 (owner 크루장 / staff 운영진 / member 크루원)",
                        default="member",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "승인 대기"), ("active", "활동 중")],
                        db_comment="상태 (pending 승인 대기 / active 활동 중)",
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="가입(활동 시작) 시각. 승인 대기 중이면 NULL",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="생성 시각", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_comment="마지막 수정 시각"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="soft delete 여부 (True면 삭제된 행)",
                        db_index=True,
                        default=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_comment="soft delete 시각", null=True
                    ),
                ),
                (
                    "crew",
                    models.ForeignKey(
                        db_comment="크루 FK",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="crews.crew",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_comment="회원 FK",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crew_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table_comment": "크루 소속 — (크루, 회원) 유일, 역할/상태, 탈퇴분은 soft delete",
            },
        ),
        migrations.AddIndex(
            model_name="crew",
            index=models.Index(fields=["name"], name="crews_crew_name_7067a8_idx"),
        ),
        migrations.AddIndex(
            model_name="crew",
            index=models.Index(
                fields=["home_gym", "-created_at"], name="crews_crew_home_gy_fb03b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crewmember",
            index=models.Index(
                fields=["crew", "status"], name="crews_crewm_crew_id_576b02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crewmember",
            index=models.Index(
                fields=["user", "status"], name="crews_crewm_user_id_6305f8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="crewmember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("crew", "user"),
                name="uniq_crew_member",
            ),
        ),
    ]
