# Generated by Django 5.1.5 on 2026-08-27 08:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gyms", "0002_location_column_comment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("free", "자유"), ("recruit", "모집")],
                        db_comment="게시글 종류 (free 자유글 / recruit 모집글)",
                        default="free",
                        max_length=10,
                    ),
                ),
                (
                    "title",
                    models.CharField(db_comment="제목 (최대 100자)", max_length=100),
                ),
                ("content", models.TextField(db_comment="본문 (최대 5000자)")),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        db_comment="조회수 (작성자 본인 조회는 제외, F() 증가)",
                        default=0,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="생성 시각", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_comment="마지막 수정 시각"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="soft delete 여부 (True면 삭제된 행)",
                        db_index=True,
                        default=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_comment="soft delete 시각", null=True
                    ),
                ),
                (
                    "gym",
                    models.ForeignKey(
                        blank=True,
                        db_comment="관련 암장 FK (선택). 암장이 지워지면 NULL",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="gyms.gym",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_comment="작성자 FK",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table_comment": "커뮤니티 게시글 — 자유글/모집글. 모집글은 Recruitment 와 1:1",
            },
        ),
        migrations.CreateModel(
            name="PostComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(db_comment="댓글 본문 (최대 500자)")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="생성 시각", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_comment="마지막 수정 시각"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="soft delete 여부 (True면 삭제된 행)",
                        db_index=True,
                        default=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_comment="soft delete 시각", null=True
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_comment="부모 댓글 FK — 1단계 대댓글만 허용 (대댓글의 대댓글 불가)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="community.postcomment",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        db_comment="게시글 FK",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="community.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_comment="작성자 FK",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table_comment": "게시글 댓글 — parent 로 1단계 대댓글",
            },
        ),
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.URLField(
                        db_comment="이미지 URL (S3, presigned URL 로 직접 업로드)"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(db_comment="노출 순서", default=0),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="생성 시각", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_comment="마지막 수정 시각"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="soft delete 여부 (True면 삭제된 행)",
                        db_index=True,
                        default=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_comment="soft delete 시각", null=True
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        db_comment="게시글 FK",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="community.post",
                    ),
                ),
            ],
            options={
                "db_table_comment": "게시글 첨부 이미지",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Recruitment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meet_at",
                    models.DateTimeField(db_comment="모임 일시 (작성 시점 기준 미래)"),
                ),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(
                        db_comment="정원 (작성자 포함, 2~50명)",
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                (
                    "join_type",
                    models.CharField(
                        choices=[("instant", "선착순"), ("approval", "승인제")],
                        db_comment="참여 방식 (instant 선착순 즉시 승인 / approval 작성자 승인제)",
                        default="instant",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "모집중"),
                            ("closed", "마감"),
                            ("canceled", "취소"),
                        ],
                        db_comment="모집 상태 (open 모집중 / closed 마감 / canceled 취소)",
                        db_index=True,
                        default="open",
                        max_length=10,
                    ),
                ),
                (
                    "chat_room_id",
                    models.PositiveIntegerField(
                        blank=True,
                        db_comment="마감 시 생성된 chat.ChatRoom id (FK 는 chat 앱 안정화 후 마이그레이션으로 전환)",
                        null=True,
                    ),
                ),
                (
                    "crew_id",
                    models.PositiveIntegerField(
                        blank=True,
                        db_comment="크루 주최 모집일 때 crews.Crew id (FK 는 crews 앱 도입 후 전환). NULL 이면 개인 모집",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="생성 시각", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_comment="마지막 수정 시각"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="soft delete 여부 (True면 삭제된 행)",
                        db_index=True,
                        default=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_comment="soft delete 시각", null=True
                    ),
                ),
                (
                    "gym",
                    models.ForeignKey(
                        db_comment="투어 대상 암장 FK",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recruitments",
                        to="gyms.gym",
                    ),
                ),
                (
                    "post",
                    models.OneToOneField(
                        db_comment="모집글 FK (category=recruit 인 Post 와 1:1)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruitment",
                        to="community.post",
                    ),
                ),
            ],
            options={
                "db_table_comment": "투어 모집 — 대상 암장/일시/정원/참여 방식/상태",
            },
        ),
        migrations.CreateModel(
            name="Participation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("approved", "승인"),
                            ("rejected", "거절"),
                            ("canceled", "취소"),
                        ],
                        db_comment="참여 상태 (pending 대기 / approved 승인 / rejected 거절 / canceled 취소)",
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="생성 시각", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_comment="마지막 수정 시각"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="soft delete 여부 (True면 삭제된 행)",
                        db_index=True,
                        default=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_comment="soft delete 시각", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_comment="참여자 FK",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recruitment",
                    models.ForeignKey(
                        db_comment="모집 FK",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="community.recruitment",
                    ),
                ),
            ],
            options={
                "db_table_comment": "모집 참여 — (모집, 회원) 유일, 취소분은 soft delete",
            },
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["category", "-created_at"],
                name="community_p_categor_e45bfb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["gym", "-created_at"], name="community_p_gym_id_3c1c18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postcomment",
            index=models.Index(
                fields=["post", "created_at"], name="community_p_post_id_c9828b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recruitment",
            index=models.Index(
                fields=["gym", "status", "meet_at"],
                name="community_r_gym_id_61c925_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="participation",
            index=models.Index(
                fields=["recruitment", "status"], name="community_p_recruit_27bb92_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="participation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("recruitment", "user"),
                name="uniq_participation",
            ),
        ),
    ]
