# Generated by Django 5.1.5 on 2026-08-27 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recruitment",
            name="chat_room_id",
        ),
        migrations.AddField(
            model_name="recruitment",
            name="chat_room",
            field=models.ForeignKey(
                blank=True,
                db_comment="마감 시 생성된 그룹 채팅방 FK. 마감 전에는 NULL",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recruitments",
                to="chat.chatroom",
            ),
        ),
    ]
