# Generated by Django 5.1.5 on 2026-08-28 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gyms", "0002_location_column_comment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GymManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, db_comment="비고 (예: 점장)", max_length=100
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="생성 시각", db_index=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_comment="마지막 수정 시각"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="soft delete 여부 (True면 삭제된 행)",
                        db_index=True,
                        default=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_comment="soft delete 시각", null=True
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="지정한 회원 FK (admin 지정 시 NULL 가능)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gym",
                    models.ForeignKey(
                        db_comment="암장 FK",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managers",
                        to="gyms.gym",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_comment="관리자 회원 FK",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gym_managements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table_comment": "암장 관리자 — 암장당 여러 명. (gym, user) 는 살아있는 행 기준 유일",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_deleted", False)),
                        fields=("gym", "user"),
                        name="uniq_gym_manager",
                    )
                ],
            },
        ),
    ]
